language: node_js
node_js: stable
sudo: required
dist: trusty
install:
  - npm cache clean
  - npm install
script:
  - npm run test
  - npm run build
deploy:
  skip_cleanup: true
  provider: azure_web_apps
  on: dev